# Generated by Django 4.1.5 on 2023-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0003_rename_author_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="authors/"),
        ),
    ]
