# Generated by Django 4.1.5 on 2023-01-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="profile",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="profile",
            new_name="author",
        ),
    ]
