# Generated by Django 4.1.5 on 2023-04-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_profile_article_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="description",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="blog.article",
            ),
        ),
    ]
