# Generated by Django 4.1.5 on 2023-01-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=228)),
                ("position", models.CharField(max_length=228)),
                ("avatar", models.ImageField(upload_to="feedbacks/")),
                ("message", models.TextField()),
            ],
        ),
    ]
